# Generated by Django 4.2 on 2023-07-05 19:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employeeapi', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Student',
            new_name='Employee',
        ),
    ]
